version: "3.5"
services:
  gateway:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - GOOGLE_APPLICATION_CREDENTIALS=google-creds.json
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
