http:
  port: ${PORT:-8080}
apiEndpoints:
  node_server:
    methods: "GET,POST,PUT"
    host: localhost
    paths: "/node_server/*"
  songs:
    methods: "GET,POST,PUT"
    host: localhost
    paths: "/songs/*"

serviceEndpoints:
  node_server_service:
    url: "https://rostov-nodeserver.herokuapp.com"
  songs_service:
    url: "https://rostov-song-server.herokuapp.com/api/v1/songs"
policies:
  - proxy
  - request-transformer
  - rewrite
pipelines:
  node_server:
    apiEndpoints:
      - node_server
    policies:
      - request-transformer:
          - action:
              headers:
                add:
                  api_key: "'key'"
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/node_server/(.*)$
            action:
              rewrite: /$1
      - proxy:
          - action:
              serviceEndpoint: node_server_service
  songs:
    apiEndpoints:
      - songs
    policies:
      - request-transformer:
          - action:
              headers:
                add:
                  api_key: "'key'"
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/songs/(.*)$
            action:
              rewrite: /$1
      - proxy:
          - action:
              serviceEndpoint: songs_service
