http:
  port: ${PORT:-8080}
  host: ${HOST:-rostov-gateway.herokuapp.com}
apiEndpoints:
  node_server:
    methods: "*"
    origin: "*"
    host: ${HOST:-rostov-gateway.herokuapp.com}
    paths: "/node_server/*"
  songs:
    methods: "*"
    origin: "*"
    host: ${HOST:-rostov-gateway.herokuapp.com}
    paths: "/songs/*"
  devsongs:
    methods: "*"
    origin: "*"
    host: ${HOST:-rostov-gateway.herokuapp.com}
    paths: "/devsongs/*"

serviceEndpoints:
  node_server_service:
    url: "https://rostov-nodeserver.herokuapp.com"
  songs_service:
    url: "http://rostov-song-server.herokuapp.com/api/v3"
  songs_dev:
    url: "https://rostov-songs-dev.herokuapp.com/api/v3"
policies:
  - cors
  - proxy
  - request-transformer
  - rewrite
  - auth
pipelines:
  songs:
    apiEndpoints:
      - songs
    policies:
      - cors:
          - action:
              methods: "*"
              origin: "*"
              credentials: true
              allowedHeaders: "*"
              preflightContinue: false
      - auth: null
      - request-transformer:
          - action:
              headers:
                add:
                  api_key: "'${SONGS_API_KEY}'"
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/songs/(.*)$
            action:
              rewrite: /$1
      - proxy:
          - action:
              serviceEndpoint: songs_service
  devsongs:
    apiEndpoints:
      - devsongs
    policies:
      - cors:
          - action:
              methods: "*"
              origin: "*"
              credentials: true
              allowedHeaders: "*"
              preflightContinue: false
      - auth: null
      - request-transformer:
          - action:
              headers:
                add:
                  api_key: "'${SONGS_API_KEY}'"
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/songs/(.*)$
            action:
              rewrite: /$1
      - proxy:
          - action:
              serviceEndpoint: songs_dev
