name: Pipeline

on:
  push:
    branches: [master]
    paths-ignore: ["**/README.md"]
  pull_request:
    branches: [master]
    paths-ignore: ["**/README.md"]
    types: [opened, synchronize]
  workflow_dispatch: # Allows manual run

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    # needs: [Lint, Test]
    runs-on: ubuntu-18.04
    environment:
      name: Production
      url: "https://rostov-gateway.herokuapp.com/"
    steps:
      - uses: actions/checkout@v3
      - name: Copy Dockerfile
        run: npm run docker:cp-root
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        env:
          HD_API_KEY: ${{secrets.API_KEY}}
          HD_GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          HD_GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}
          HD_SONGS_API_KEY: ${{secrets.SONGS_API_KEY}}
          HD_NOTIFICATIONS_API_KEY: ${{secrets.NOTIFICATIONS_API_KEY}}
        with:
          usedocker: true
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # healthcheck: "https://${{secrets.HEROKU_NAME}}.herokuapp.com/api/health"
          # rollbackonhealthcheckfailed: true
          # delay: 1.5
